spring:
  datasource:
    url: jdbc:mysql://192.168.168.150:3306/springboot_admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.168.150